import { Instrument, Certificate, Business, Inspector, NotificationItem } from '../types';

export const MOCK_INSTRUMENTS: Instrument[] = [
  {
    id: 'IMP-MH-162-2026',
    verificationId: 'IMP-MH-162-2026',
    certificateNumber: 'IMP/MH/162/2026',
    instrumentType: 'All types of weighing and measuring instruments',
    type: 'Electronic Weighing Scale',
    manufacturer: 'Registered Overseas Manufacturer / Importer',
    model: 'Approved Model under Legal Metrology Importers Portal',
    modelNumber: 'SUPREME-TECH-2026',
    serialNumber: '0316936936',
    capacity: 'As per approved Certificate specification',
    accuracyClass: 'Class II / Class III (High / Medium Accuracy)',
    ownerName: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    businessId: 'BUS-MH-162',
    businessName: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    businessAddress: 'Registered Corporate Office, Maharashtra, India',
    district: 'Maharashtra Directorate',
    state: 'Maharashtra',
    installationDate: '16/09/2026',
    prevCertNo: 'IMP/MH/162/2025',
    status: 'VERIFIED',
    verificationStatus: 'VERIFIED',
    lastVerificationDate: '16/09/2026',
    verificationDate: '16/09/2026',
    validUntil: '15/09/2031',
    inspectorName: 'Controller of Legal Metrology',
    inspectorId: 'CLM-GOI-01',
    qrVerificationUrl: 'http://localhost:3000/verify/IMP-MH-162-2026',
    importerName: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    registrationNo: '0316936936',
    issueDateStr: '16/09/2026',
    validityDateStr: '15/09/2031',
    itemCategory: 'All types of weighing and measuring instruments',
    sourceType: 'OFFICIAL_REFERENCE',
    sourceReference: 'Department of Consumer Affairs, Government of India — Certificates of Importers Portal (https://consumeraffairs.gov.in/)'
  },
  {
    id: 'IMP-MH-159-2026',
    verificationId: 'IMP-MH-159-2026',
    certificateNumber: 'IMP/MH/159/2026',
    instrumentType: 'All types of weighing and measuring instrument, Measuring Tape, Load Cell, Water Meter',
    type: 'Water & Flow Meter',
    manufacturer: 'Sensus Metering India Private Limited',
    model: 'SENSUS-WATER-METER-F900',
    modelNumber: 'SENSUS-F900',
    serialNumber: 'ABRCS2286B',
    capacity: 'As per approved Certificate specification',
    accuracyClass: 'Class I / Class II',
    ownerName: 'SENSUS METERING INDIA PRIVATE LIMITED',
    businessId: 'BUS-MH-159',
    businessName: 'SENSUS METERING INDIA PRIVATE LIMITED',
    businessAddress: 'Registered Office, Maharashtra, India',
    district: 'Maharashtra Directorate',
    state: 'Maharashtra',
    installationDate: '09/09/2026',
    prevCertNo: 'IMP/MH/159/2025',
    status: 'VERIFIED',
    verificationStatus: 'VERIFIED',
    lastVerificationDate: '09/09/2026',
    verificationDate: '09/09/2026',
    validUntil: '08/09/2031',
    inspectorName: 'Controller of Legal Metrology',
    inspectorId: 'CLM-GOI-01',
    qrVerificationUrl: 'http://localhost:3000/verify/IMP-MH-159-2026',
    importerName: 'SENSUS METERING INDIA PRIVATE LIMITED',
    registrationNo: 'ABRCS2286B',
    issueDateStr: '09/09/2026',
    validityDateStr: '08/09/2031',
    itemCategory: 'All types of weighing and measuring instrument, Measuring Tape, Load Cell, Water Meter',
    sourceType: 'OFFICIAL_REFERENCE',
    sourceReference: 'Department of Consumer Affairs, Government of India — Certificates of Importers Portal (https://consumeraffairs.gov.in/)'
  },
  {
    id: 'IMP-GJ-157-2026',
    verificationId: 'IMP-GJ-157-2026',
    certificateNumber: 'IMP/GJ/157/2026',
    instrumentType: 'All types of weighing and measuring instruments, Water meter, Gas meter, Flow meter',
    type: 'Retail Weighing Instrument',
    manufacturer: 'National Instruments Solutions',
    model: 'NIS-FLOWMETER-2026',
    modelNumber: 'NIS-2026',
    serialNumber: 'APSPP2837D',
    capacity: 'As per approved Certificate specification',
    accuracyClass: 'Class II (High Accuracy)',
    ownerName: 'NATIONAL INSTRUMENTS SOLUTIONS',
    businessId: 'BUS-GJ-157',
    businessName: 'NATIONAL INSTRUMENTS SOLUTIONS',
    businessAddress: 'Registered Office, Gujarat, India',
    district: 'Gujarat Directorate',
    state: 'Gujarat',
    installationDate: '01/09/2026',
    prevCertNo: 'IMP/GJ/157/2025',
    status: 'VERIFIED',
    verificationStatus: 'VERIFIED',
    lastVerificationDate: '01/09/2026',
    verificationDate: '01/09/2026',
    validUntil: '31/08/2031',
    inspectorName: 'Controller of Legal Metrology',
    inspectorId: 'CLM-GOI-01',
    qrVerificationUrl: 'http://localhost:3000/verify/IMP-GJ-157-2026',
    importerName: 'NATIONAL INSTRUMENTS SOLUTIONS',
    registrationNo: 'APSPP2837D',
    issueDateStr: '01/09/2026',
    validityDateStr: '31/08/2031',
    itemCategory: 'All types of weighing and measuring instruments, Water meter, Gas meter, Flow meter',
    sourceType: 'OFFICIAL_REFERENCE',
    sourceReference: 'Department of Consumer Affairs, Government of India — Certificates of Importers Portal (https://consumeraffairs.gov.in/)'
  }
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    certificateNumber: 'IMP/MH/162/2026',
    instrumentId: 'IMP-MH-162-2026',
    verificationId: 'IMP-MH-162-2026',
    instrumentType: 'All types of weighing and measuring instruments',
    manufacturer: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    serialNumber: '0316936936',
    businessName: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    businessAddress: 'Registered Corporate Office, Maharashtra, India',
    district: 'Maharashtra Directorate',
    state: 'Maharashtra',
    issueDate: '16/09/2026',
    validUntil: '15/09/2031',
    inspectorName: 'Controller of Legal Metrology',
    inspectorId: 'CLM-GOI-01',
    status: 'VALID',
    qrCodeUrl: 'http://localhost:3000/verify/IMP-MH-162-2026',
    sealId: 'SEAL-LM-2026-162',
    sourceType: 'OFFICIAL_REFERENCE',
    sourceReference: 'Department of Consumer Affairs, Government of India'
  },
  {
    certificateNumber: 'IMP/MH/159/2026',
    instrumentId: 'IMP-MH-159-2026',
    verificationId: 'IMP-MH-159-2026',
    instrumentType: 'All types of weighing and measuring instrument, Measuring Tape, Load Cell, Water Meter',
    manufacturer: 'SENSUS METERING INDIA PRIVATE LIMITED',
    serialNumber: 'ABRCS2286B',
    businessName: 'SENSUS METERING INDIA PRIVATE LIMITED',
    businessAddress: 'Registered Office, Maharashtra, India',
    district: 'Maharashtra Directorate',
    state: 'Maharashtra',
    issueDate: '09/09/2026',
    validUntil: '08/09/2031',
    inspectorName: 'Controller of Legal Metrology',
    inspectorId: 'CLM-GOI-01',
    status: 'VALID',
    qrCodeUrl: 'http://localhost:3000/verify/IMP-MH-159-2026',
    sealId: 'SEAL-LM-2026-159',
    sourceType: 'OFFICIAL_REFERENCE',
    sourceReference: 'Department of Consumer Affairs, Government of India'
  }
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'BUS-MH-162',
    name: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    ownerName: 'SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED',
    tradeLicenseNo: '0316936936',
    gstin: '27AAAAA0000A1Z5',
    category: 'Importers of Weights & Measures',
    address: 'Registered Corporate Office, Maharashtra, India',
    district: 'Maharashtra Directorate',
    state: 'Maharashtra',
    phone: '+91 22 2840 1000',
    email: 'info@supreme-instruments.com',
    registeredDate: '16/09/2026',
    totalInstruments: 12
  },
  {
    id: 'BUS-MH-159',
    name: 'SENSUS METERING INDIA PRIVATE LIMITED',
    ownerName: 'SENSUS METERING INDIA PRIVATE LIMITED',
    tradeLicenseNo: 'ABRCS2286B',
    gstin: '27BBBBB1111B2Z6',
    category: 'Water & Flow Meter Importers',
    address: 'Registered Office, Maharashtra, India',
    district: 'Maharashtra Directorate',
    state: 'Maharashtra',
    phone: '+91 22 6750 2000',
    email: 'contact@sensus-metering.in',
    registeredDate: '09/09/2026',
    totalInstruments: 8
  }
];

export const MOCK_INSPECTORS: Inspector[] = [
  {
    id: 'CLM-GOI-01',
    badgeNumber: 'CLM-GOI-2026',
    name: 'Controller of Legal Metrology',
    designation: 'Central Legal Metrology Directorate',
    district: 'Central Headquarters',
    state: 'Government of India',
    phone: '+91 11 2338 1234',
    email: 'controller-lm@gov.in',
    assignedCount: 163,
    completedCount: 163,
    activeSince: '2015'
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    title: 'Importer Registration Certificate Issued',
    message: 'Certificate IMP/MH/162/2026 issued for SUPREME INSTRUMENT TECHNOLOGY PRIVATE LIMITED.',
    timestamp: '10 minutes ago',
    read: false,
    type: 'success',
    link: '/certificate/IMP-MH-162-2026'
  },
  {
    id: 'NOTIF-2',
    title: 'Portal Database Synchronized',
    message: 'All statutory records from Department of Consumer Affairs Legal Metrology Portal are active.',
    timestamp: '1 hour ago',
    read: false,
    type: 'info',
    link: '/verify'
  }
];
